version: '3'
services:
    web:
        build: .
        ports:
         - "80:8000"
        volumes:
         - .:/code
        stdin_open: true
        tty: true
        depends_on: 
         - database

    database:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        volumes:
         - pgdata:/var/lib/postgresql/data

    adminer:
        image: 'adminer'
        ports:
          - '8080:8080'
volumes:
    pgdata:
