version: "3"

services:
    producer:
        build: ./producer

    consumer:
        build: ./consumer

    rabbitmq:
        image: "rabbitmq:alpine"

    postgres:
        image: 'postgres'
        expose:
         - 5432
        environment:
            POSTGRES_PASSWORD: 'postgres'
            PGDATA: '/var/lib/postgresql/data/pgdata'
